import Head from 'next/head';
import CustomTitle from '@/components/layout/custom-title';
import Navbar from '@/components/layout/navbar';
import HomeBanner from '@/components/home/home-banner';
import HomeCatalogueSection from '@/components/home/home-catalogue-section';
import HomeArticlesSection from '@/components/home/home-articles-section';
import HomeAboutMeSection from '@/components/home/home-aboutme-section';


import styles from '@/styles/Home.module.css';

export default function HomePage() {
  return (
    <>
      <Head>
        <CustomTitle titlePage={"Florist Pedia | Learn More About Your House Plants"}/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        <HomeBanner />
        <HomeCatalogueSection />
        <HomeArticlesSection />
        <HomeAboutMeSection />
    </>
  )
}
